[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
array2d = { git = "https://github.com/klevente/array2d" }
itertools = "0.10.1"
phf = { version = "0.11.1", features = ["macros"] }
sscanf = "0.3.1"

[[bin]]
name = "day1"
path = "src/day1.rs"
